name: qrcode_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_main.png"